######################################################################
# Automatically generated by qmake (3.0) Tue Jul 26 06:04:36 2016
######################################################################
QT += core gui widgets
TEMPLATE = app
TARGET = CubeEye
INCLUDEPATH += .

# Input
HEADERS += cubeeye.h MTF_API.h
FORMS += cubeeye.ui
SOURCES += cubeeye.cpp main.cpp
LIBS += -lMTF_API
